#!/bin/bash

set -eoux pipefail

main() {
  if [ "$CI" ]; then
    ./node_modules/.bin/prettier --check '**/*.{js,tsx,ts,md,yml,json}'
  else
    ./node_modules/.bin/prettier '**/*.{js,tsx,ts,md,yml,json}' --write
  fi
}

main "$@" 

