#!/usr/bin/env bash
set -eoux pipefail

main() {
  if [ "$CI" ]; then
    node_modules/.bin/eslint 'src/**/*.{ts,tsx,js,jsx}'
  else
    node_modules/.bin/eslint 'src/**/*.{ts,tsx,js,jsx}' --fix --cache
  fi
}

main "$@"
