# AUTOGENERATED FROM 'foodieyak/queries/create_session.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateSessionResult(NoPydanticValidation):
    id: uuid.UUID
    key: uuid.UUID


async def create_session(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> CreateSessionResult:
    return await executor.query_single(
        """\
        with session := (insert Session {
          user := (select User filter .id = <uuid>$user_id)
        }) 
        select session {key}\
        """,
        user_id=user_id,
    )
