# AUTOGENERATED FROM 'foodieyak/queries/create_team.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateTeamResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def create_team(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    user_id: uuid.UUID,
) -> CreateTeamResult:
    return await executor.query_single(
        """\
        with new_team := (insert Team {
          name := <str>$name,
          members := (select User filter .id = <uuid>$user_id limit 1)
        }) 
        select new_team {
          name
        }\
        """,
        name=name,
        user_id=user_id,
    )
