# AUTOGENERATED FROM 'foodieyak/queries/create_team_invite.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateTeamInviteResult(NoPydanticValidation):
    id: uuid.UUID
    sender: CreateTeamInviteResultSender
    recipient: CreateTeamInviteResultSender
    team: CreateTeamInviteResultTeam


@dataclasses.dataclass
class CreateTeamInviteResultSender(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class CreateTeamInviteResultTeam(NoPydanticValidation):
    id: uuid.UUID


async def create_team_invite(
    executor: edgedb.AsyncIOExecutor,
    *,
    sender_id: uuid.UUID,
    recipient_id: uuid.UUID,
    team_id: uuid.UUID,
) -> CreateTeamInviteResult:
    return await executor.query_single(
        """\
        with new_invite := (insert TeamInvite {
          sender :=  <User>$sender_id,
          recipient := <User>$recipient_id,
          team := <Team>$team_id
        }) 
        select new_invite {
          sender,
          recipient,
          team,
        }\
        """,
        sender_id=sender_id,
        recipient_id=recipient_id,
        team_id=team_id,
    )
