# AUTOGENERATED FROM 'foodieyak/queries/get_user_by_email.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByEmailResult(NoPydanticValidation):
    id: uuid.UUID
    email: str
    password_hash: str


async def get_user_by_email(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> GetUserByEmailResult | None:
    return await executor.query_single(
        """\
        select User {
          email,
          password_hash,
        }
        filter .email = str_lower(<str>$email)
        limit 1\
        """,
        email=email,
    )
