# AUTOGENERATED FROM 'foodieyak/queries/get_user_by_session_key.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserBySessionKeyResult(NoPydanticValidation):
    id: uuid.UUID
    name: str | None
    email: str


async def get_user_by_session_key(
    executor: edgedb.AsyncIOExecutor,
    *,
    session_key: uuid.UUID,
) -> GetUserBySessionKeyResult | None:
    return await executor.query_single(
        """\
        select User {
          name,
          email
        }
        filter .<user[is Session].key = <uuid>$session_key
        limit 1;\
        """,
        session_key=session_key,
    )
