#!/usr/bin/env bash
set -ex

docker_image_name="api"

main() {
  local project_id="${1}"; shift
  local artifact_registry_domain="${1}"; shift
  local artifact_registry_repository="${1}"; shift
  local git_sha="${1}"; shift

  local tag="${artifact_registry_domain}/${project_id}/${artifact_registry_repository}/${docker_image_name}:${git_sha}"
  docker build --tag "${tag}" .
  docker push "${tag}"

  echo "image_tag=${tag}" >> "$GITHUB_OUTPUT"
  echo "Pushed \`${tag}\`" >> "$GITHUB_STEP_SUMMARY"
}
main "$@"
