#!/usr/bin/env python3
import argparse
import json
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--service-name", required=True)
parser.add_argument("--image", required=True)
parser.add_argument("--region", required=True)
parser.add_argument("--pr-number")


def main():
    args = parser.parse_args()
    cmd = [
        "gcloud",
        "run",
        "deploy",
        args.service_name,
        f"--image={args.image}",
        f"--region={args.region}",
        "--format=json",
    ]
    tag = f"pr-{args.pr_number}" if args.pr_number else None

    if tag:
        cmd.append(f"--tag={tag}")
    res = subprocess.run(cmd, check=True, capture_output=True)
    data = json.loads(res.stdout)

    if tag:
        for traffic in data["status"]["traffic"]:
            if traffic.get("tag") == tag:
                print(traffic["url"])
                return
    print(data["status"]["url"])


if __name__ == "__main__":
    main()
