name: API
"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  # api_staging:
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: staging-api
  #     url: https://staging.foodieyak.com/api

  #   defaults:
  #     run:
  #       working-directory: "./api"

  #   env:
  #     FIREBASE_GOOGLE_SERVICE_ACCOUNT_CERTIFICATE: ${{ secrets.FIREBASE_GOOGLE_SERVICE_ACCOUNT_CERTIFICATE }}

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version-file: "./package.json"
  #     - uses: pnpm/action-setup@v2
  #       name: Install pnpm
  #       with:
  #         version: 8
  #         run_install: false

  #     - name: Get pnpm store directory
  #       shell: bash
  #       run: |
  #         echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

  #     - uses: actions/cache@v3
  #       name: Setup pnpm cache
  #       with:
  #         path: ${{ env.STORE_PATH }}
  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pnpm-store-

  #     - name: Install dependencies
  #       run: pnpm install
  #     - run: s/deploy-stage
  stage_deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: "foodieyak-staging"
      ARTIFACT_REGISTRY_DOMAIN: "us-central1-docker.pkg.dev"
      ARTIFACT_REGISTRY_REPOSITORY: "foodieyak-api"

    environment:
      name: staging-api
      url: https://foodieyak.com/api

    defaults:
      run:
        working-directory: "./api"

    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v2"
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}"
      - uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      - uses: docker/setup-buildx-action@v2
      - run: gcloud auth list
      - run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_DOMAIN }}
      - name: Build and push
        run: s/build-and-push ${{ env.PROJECT_ID }} ${{ env.ARTIFACT_REGISTRY_DOMAIN }} ${{ env.ARTIFACT_REGISTRY_REPOSITORY }} ${{ github.event.pull_request.head.sha || github.sha }}
