name: Deploy Functions
"on": pull_request
jobs:
  staging:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./functions"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - name: install
        run: yarn install
      - name: install
        run: s/deploy-stage
  production:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./functions"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - name: install
        run: yarn install
      - name: install
        run: s/deploy-prod
