name: Deploy
"on":
  push:
    branches:
      - main
jobs:
  functions_staging:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://staging.foodieyak.com

    defaults:
      run:
        working-directory: "./functions"

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_LOGIN_TOKEN }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - run: s/deploy-stage
  functions_production:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://foodieyak.com

    defaults:
      run:
        working-directory: "./functions"

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_LOGIN_TOKEN }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - run: s/deploy-prod

  ui_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
        working-directory: "./ui"
      - run: pnpm build
        working-directory: "./ui"
      - uses: chdsbd/action-hosting-deploy@chris/disable-comments
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODIEYAK_EF36D }}"
          channelId: live
          projectId: foodieyak-ef36d
          entryPoint: "./ui"

  ui_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./package.json"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
        working-directory: "./ui"
      - run: pnpm build
        working-directory: "./ui"
      - uses: chdsbd/action-hosting-deploy@chris/disable-comments
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODIEYAK_EF36D }}"
          channelId: live
          projectId: foodieyak-ef36d
          entryPoint: "./ui"
