name: Deploy
"on":
  push:
    branches:
      - main
jobs:
  functions_staging:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://staging.foodieyak.com

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_LOGIN_TOKEN }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}

    steps:
      - uses: ./.github/workflows/foodieyak-job.yml
        with:
          working-directory: "./functions"
          run: s/deploy-stage

  functions_production:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://foodieyak.com

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_LOGIN_TOKEN }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}

    steps:
      - uses: ./.github/workflows/foodieyak-job.yml
        with:
          working-directory: "./functions"
          run: s/deploy-prod

  ui_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/foodieyak-job.yml
        with:
          working-directory: "./ui"
          run: pnpm build
      - uses: chdsbd/action-hosting-deploy@chris/disable-comments
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODIEYAK_EF36D }}"
          channelId: live
          projectId: foodieyak-ef36d
          entryPoint: "./ui"

  ui_production:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/foodieyak-job.yml
        with:
          working-directory: "./ui"
          run: pnpm build
      - uses: chdsbd/action-hosting-deploy@chris/disable-comments
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOODIEYAK_EF36D }}"
          channelId: live
          projectId: foodieyak-ef36d
          entryPoint: "./ui"
