name: Test

on:
  pull_request:

jobs:
  typecheck_ui:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "typecheck_ui"
    with:
      working-directory: "./ui"
      run: "./s/typecheck"

  test_ui:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::add-matcher::.github/problem-matcher-vitest.json"
      - uses: ./.github/workflows/foodieyak-job.yml
        name: "test_ui"
        with:
          working-directory: "./ui"
          run: "./s/test"
      - run: echo "::remove-matcher::.github/problem-matcher-vitest.json"

  lint_ui:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "lint_ui"
    with:
      working-directory: "./ui"
      run: "./s/lint"

  fmt_ui:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "fmt_ui"
    with:
      working-directory: "./ui"
      run: "./s/fmt"

  typecheck_functions:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "typecheck_functions"
    with:
      working-directory: "./functions"
      run: "./s/typecheck"

  lint_functions:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "lint_functions"
    with:
      working-directory: "./functions"
      run: "./s/lint"

  fmt_functions:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "fmt_functions"
    with:
      working-directory: "./functions"
      run: "./s/fmt"
