name: Javascript

on:
  pull_request:

jobs:
  typecheck_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./ui/package.json"
          cache-dependency-path: "./ui/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "./ui"
        run: yarn install
      - name: Typescript
        working-directory: "./ui"
        run: ./s/typecheck

  lint_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./ui/package.json"
          cache-dependency-path: "./ui/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "./ui"
        run: yarn install
      - name: Lint
        working-directory: "./ui"
        run: ./s/lint

  fmt_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./ui/package.json"
          cache-dependency-path: "./ui/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "./ui"
        run: yarn install
      - name: Check Formatting
        working-directory: "./ui"
        run: ./s/fmt

  typecheck_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./functions/package.json"
          cache-dependency-path: "./functions/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "./functions"
        run: yarn install
      - name: Typescript
        working-directory: "./functions"
        run: ./s/typecheck

  lint_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./functions/package.json"
          cache-dependency-path: "./functions/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "./functions"
        run: yarn install
      - name: Lint
        working-directory: "./functions"
        run: ./s/lint

  fmt_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./fucntions/package.json"
          cache-dependency-path: "./fucntions/yarn.lock"
          cache: "yarn"
      - name: Install dependencies
        working-directory: "./functions"
        run: yarn install
      - name: Check Formatting
        working-directory: "./functions"
        run: ./s/fmt
