name: UI

on:
  pull_request:

jobs:
  typecheck:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "typecheck"
    with:
      working-directory: "./ui"
      run: "./s/typecheck"
  lint:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "lint"
    with:
      working-directory: "./ui"
      run: "./s/lint"
  format:
    uses: ./.github/workflows/foodieyak-job.yml
    name: "format"
    with:
      working-directory: "./ui"
      run: "./s/fmt"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::add-matcher::.github/problem-matcher-vitest.json"
      - name: test
        uses: ./.github/workflows/foodieyak-job.yml
        with:
          working-directory: "./ui"
          run: ./s/test
      - run: echo "::remove-matcher::.github/problem-matcher-vitest.json"
